/**
 * seeds/hyakumeizan.csv を D1 に投入する。
 *
 *   npx tsx scripts/seed.ts --local     # ローカル（wrangler dev 用）
 *   npx tsx scripts/seed.ts --remote    # 本番 D1
 *   npx tsx scripts/seed.ts --sql-only  # SQL を書き出すだけ
 *
 * 既存行は INSERT OR REPLACE で上書きする（座標を手で直した後に再投入すると
 * 元に戻ってしまうので、手修正は /settings 経由で行い CSV にも反映すること）。
 */
import { spawnSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { toRecords } from './lib/csv';

const CSV_PATH = resolve(process.cwd(), 'seeds/hyakumeizan.csv');
const SQL_PATH = resolve(process.cwd(), 'seeds/hyakumeizan.sql');

const quote = (v: string | null) => (v === null ? 'NULL' : `'${v.replace(/'/g, "''")}'`);
const nullable = (v: string) => (v.trim() === '' ? null : v.trim());

async function main() {
  const local = process.argv.includes('--local');
  const remote = process.argv.includes('--remote');
  const sqlOnly = process.argv.includes('--sql-only');

  const records = toRecords(await readFile(CSV_PATH, 'utf8'));
  const values: string[] = [];
  const skipped: string[] = [];

  for (const r of records) {
    if (nullable(r.lat) === null || nullable(r.lng) === null) {
      skipped.push(`${r.id} ${r.name}`);
      continue;
    }
    values.push(
      `(${Number(r.id)}, ${quote(r.name)}, ${quote(nullable(r.name_kana))}, ${Number(r.elevation)}, ` +
        `${Number(r.lat)}, ${Number(r.lng)}, ${quote(nullable(r.area))}, ${quote(nullable(r.prefectures))}, ` +
        `1, ${Number(r.match_radius_m) || 3000}, ${quote(nullable(r.peak_alias))}, ${r.verified === '1' ? 1 : 0})`,
    );
  }

  if (skipped.length) {
    console.warn(`座標が空のためスキップします（${skipped.length}件）: ${skipped.join(', ')}`);
    console.warn('  → npx tsx scripts/fetch-coords.ts で補完してください');
  }
  if (values.length === 0) {
    console.error('投入できる行がありません');
    process.exit(1);
  }

  const sql =
    `-- generated by scripts/seed.ts (${new Date().toISOString()})\n` +
    `INSERT OR REPLACE INTO mountains\n` +
    `  (id, name, name_kana, elevation, lat, lng, area, prefectures, is_hyakumeizan, match_radius_m, peak_alias, verified)\n` +
    `VALUES\n${values.join(',\n')};\n`;

  await writeFile(SQL_PATH, sql, 'utf8');
  console.log(`${SQL_PATH} に ${values.length} 件を書き出しました`);

  if (sqlOnly || (!local && !remote)) {
    console.log('D1 へ投入するには --local か --remote を付けて実行してください');
    return;
  }

  const args = ['wrangler', 'd1', 'execute', 'yamalog', `--file=${SQL_PATH}`, local ? '--local' : '--remote', '-y'];
  console.log(`$ npx ${args.join(' ')}`);
  const res = spawnSync('npx', args, { stdio: 'inherit' });
  process.exit(res.status ?? 1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
